/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locationdevoiture;

import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author jb_wi
 */
public class DonneePanel extends javax.swing.JPanel {

    /**
     * Creates new form DonneePanel
     */
    public DonneePanel() {
        initComponents();
        retour = new JPanel();
    }
    
    
    public void setRetour(JPanel retour)
    {
        this.retour = retour;
    }
        
    // Fonction du panneau taux
    public void setJour(String jour)
    {
        this.jourLabel.setText(jour);
    }
    
    public void setSemaine(String semaine)
    {
        this.semaineLabel.setText(semaine);
    }
    
    public void setMois(String mois)
    {
        this.moisLabel.setText(mois);
    }
    
    public String getNouveauJour()
    {
        return this.jourTextField.getText();
    }
    
    public String getNouvelleSemaine()
    {
        return this.semaineTextField.getText();
    }
    
    public String getNouveauMois()
    {
        return this.moisTextField.getText();
    }
    
    // Fonction pour panneau gestion de vehicule    
    public String getClasseVehicule()
    {
        return this.classeComboBox.getSelectedItem().toString();
    }
    
    // Fonction pour panneau ajout de vehicule
    public String getMarque()
    {
        return this.marqueTextField.getText();
    }
    
    public String getModele()
    {
        return this.modeleTextField.getText();
    }
    
    public String getCouleur()
    {
        return this.couleurTextField.getText();
    }
    
    public String getAnnee()
    {
        return this.anneeTextField.getText();
    }
    
    public String getKilometrage()
    {
        return this.kilometrageTextField.getText();
    }
    
    public String getEssence()
    {
        return this.essenceTextField.getText();
    }
    
    public String getImmatriculation()
    {
        return this.immatriculationTextField.getText();
    }
    
    // Fonction pour panneau retirer des vehicules
    public String[] getVehiculesSelectionnes()
    {
        List<String> liste = this.vehiculeList.getSelectedValuesList();
        return liste.toArray(new String[0]);
    }
    
    public void setListeVehicule(String[] vehicules)
    {
        JList<String> jlist = new JList<String>(vehicules);
        DefaultListModel<String> liste = (DefaultListModel<String>)jlist.getModel();
        this.vehiculeList.setModel(liste);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tauxPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tauxButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jourLabel = new javax.swing.JLabel();
        semaineLabel = new javax.swing.JLabel();
        moisLabel = new javax.swing.JLabel();
        jourTextField = new javax.swing.JFormattedTextField();
        semaineTextField = new javax.swing.JFormattedTextField();
        moisTextField = new javax.swing.JFormattedTextField();
        vehiculePanel = new javax.swing.JPanel();
        ajouterPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        marqueTextField = new javax.swing.JTextField();
        modeleTextField = new javax.swing.JTextField();
        couleurTextField = new javax.swing.JTextField();
        anneeTextField = new javax.swing.JTextField();
        kilometrageTextField = new javax.swing.JTextField();
        essenceTextField = new javax.swing.JTextField();
        immatriculationTextField = new javax.swing.JTextField();
        ajouterVehiculeButton = new javax.swing.JButton();
        classeComboBox = new javax.swing.JComboBox<>();
        ajouterButton = new javax.swing.JButton();
        retirerButton = new javax.swing.JButton();
        retirerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehiculeList = new javax.swing.JList<>();
        retirerVehiculeButton = new javax.swing.JButton();
        retourButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 550));

        tauxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Changement des taux"));

        jLabel1.setText("Journalier :");

        jLabel2.setText("Hebdomadaire :");

        jLabel3.setText("Mensuel :");

        tauxButton.setText("Appliquer");
        tauxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tauxButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Présent");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Changement");

        jourLabel.setText("**.**");

        semaineLabel.setText("**.**");

        moisLabel.setText("**.**");

        jourTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        semaineTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        moisTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout tauxPanelLayout = new javax.swing.GroupLayout(tauxPanel);
        tauxPanel.setLayout(tauxPanelLayout);
        tauxPanelLayout.setHorizontalGroup(
            tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tauxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tauxButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jourLabel)
                    .addComponent(semaineLabel)
                    .addComponent(moisLabel))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jourTextField)
                        .addComponent(semaineTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(moisTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        tauxPanelLayout.setVerticalGroup(
            tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tauxPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(tauxPanelLayout.createSequentialGroup()
                        .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tauxPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(23, 23, 23)
                                .addComponent(jourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(semaineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(moisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tauxPanelLayout.createSequentialGroup()
                                .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jourLabel)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(semaineLabel)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(moisLabel)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(tauxButton))))
        );

        vehiculePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des véhicules"));

        ajouterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter"));

        jLabel6.setText("Marque :");

        jLabel7.setText("Modèle :");

        jLabel8.setText("Couleur :");

        jLabel9.setText("Kilométrage :");

        jLabel10.setText("Année :");

        jLabel11.setText("Niveau essence :");

        jLabel12.setText("Immatriculation :");

        ajouterVehiculeButton.setText("Ajouter");
        ajouterVehiculeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterVehiculeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajouterPanelLayout = new javax.swing.GroupLayout(ajouterPanel);
        ajouterPanel.setLayout(ajouterPanelLayout);
        ajouterPanelLayout.setHorizontalGroup(
            ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajouterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modeleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(couleurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kilometrageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anneeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(essenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(immatriculationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ajouterVehiculeButton)
                .addContainerGap())
        );
        ajouterPanelLayout.setVerticalGroup(
            ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(marqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(modeleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(couleurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(anneeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kilometrageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(essenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(immatriculationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ajouterVehiculeButton)
                .addContainerGap())
        );

        classeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economique", "Moyenne", "Confort", "Luxe", "Utilitaire" }));

        ajouterButton.setText("Ajouter");
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        retirerButton.setText("Retirer");
        retirerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerButtonActionPerformed(evt);
            }
        });

        retirerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Retirer"));

        vehiculeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(vehiculeList);

        retirerVehiculeButton.setText("Retirer");
        retirerVehiculeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerVehiculeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout retirerPanelLayout = new javax.swing.GroupLayout(retirerPanel);
        retirerPanel.setLayout(retirerPanelLayout);
        retirerPanelLayout.setHorizontalGroup(
            retirerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retirerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(retirerVehiculeButton))
        );
        retirerPanelLayout.setVerticalGroup(
            retirerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retirerPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, retirerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retirerVehiculeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout vehiculePanelLayout = new javax.swing.GroupLayout(vehiculePanel);
        vehiculePanel.setLayout(vehiculePanelLayout);
        vehiculePanelLayout.setHorizontalGroup(
            vehiculePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculePanelLayout.createSequentialGroup()
                .addGroup(vehiculePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiculePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(vehiculePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vehiculePanelLayout.createSequentialGroup()
                                .addComponent(ajouterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(retirerButton))))
                    .addComponent(retirerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajouterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vehiculePanelLayout.setVerticalGroup(
            vehiculePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculePanelLayout.createSequentialGroup()
                .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiculePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterButton)
                    .addComponent(retirerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retirerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
            .addGroup(vehiculePanelLayout.createSequentialGroup()
                .addComponent(ajouterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ajouterPanel.setVisible(false);

        retourButton.setText("Retour");
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(retourButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vehiculePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tauxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehiculePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tauxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retourButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tauxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tauxButtonActionPerformed
        Controller.changerTaux();
    }//GEN-LAST:event_tauxButtonActionPerformed

    private void ajouterVehiculeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterVehiculeButtonActionPerformed
        Controller.ajouterVehicule();
    }//GEN-LAST:event_ajouterVehiculeButtonActionPerformed

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        ajouterPanel.setVisible(true);
        retirerPanel.setVisible(false);
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        Controller.retourAcceuil(this, retour);
    }//GEN-LAST:event_retourButtonActionPerformed

    private void retirerVehiculeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerVehiculeButtonActionPerformed
        Controller.retirerVehicule();
        Controller.setListeVehicule();
    }//GEN-LAST:event_retirerVehiculeButtonActionPerformed

    private void retirerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerButtonActionPerformed
        ajouterPanel.setVisible(false);
        retirerPanel.setVisible(true);
        Controller.setListeVehicule();
    }//GEN-LAST:event_retirerButtonActionPerformed

    private JPanel retour;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JPanel ajouterPanel;
    private javax.swing.JButton ajouterVehiculeButton;
    private javax.swing.JTextField anneeTextField;
    private javax.swing.JComboBox<String> classeComboBox;
    private javax.swing.JTextField couleurTextField;
    private javax.swing.JTextField essenceTextField;
    private javax.swing.JTextField immatriculationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jourLabel;
    private javax.swing.JFormattedTextField jourTextField;
    private javax.swing.JTextField kilometrageTextField;
    private javax.swing.JTextField marqueTextField;
    private javax.swing.JTextField modeleTextField;
    private javax.swing.JLabel moisLabel;
    private javax.swing.JFormattedTextField moisTextField;
    private javax.swing.JButton retirerButton;
    private javax.swing.JPanel retirerPanel;
    private javax.swing.JButton retirerVehiculeButton;
    private javax.swing.JButton retourButton;
    private javax.swing.JLabel semaineLabel;
    private javax.swing.JFormattedTextField semaineTextField;
    private javax.swing.JButton tauxButton;
    private javax.swing.JPanel tauxPanel;
    private javax.swing.JList<String> vehiculeList;
    private javax.swing.JPanel vehiculePanel;
    // End of variables declaration//GEN-END:variables
}
