/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locationdevoiture;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;

/**
 *
 * @author jb_wi
 */
public class LocationPanel extends javax.swing.JPanel {

    /**
     * Creates new form locationPanel
     */
    public LocationPanel() {
        initComponents();
    }
    
    // Fonction pour vérifier le RadioButton sélectionné
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    public void setAnnuler(JPanel annuler)
    {
        this.annuler = annuler;
    }
    
    public void setConfirmer(JPanel confirmer)
    {
        this.confirmer = confirmer;
    }
    
    // Fonctions pour le paneau de paiement
    public String getModePaiement()
    {
        return this.modePaiementLocationComboBox.getSelectedItem().toString();
    }
    
    public void setPremierPaiement(String montant)
    {
        this.montantPremierVersementLabel.setText(montant);
    }
    
    public void setCaution(String montant)
    {
        this.paiementCautionLabel.setText(montant);
    }
    
    // Fonctions pour le paneau de location
    public String getDureeLocation()
    {
        return this.dureeComboBox.getSelectedItem().toString();
    }
    
    public String getDateDeLocation()
    {
        return this.dateFormattedTextField.getText();
    }
    
    public String getClasseVehicule()
    {
        return this.classeComboBox.getSelectedItem().toString();
    }
    
    public String getAssurance()
    {
        return getSelectedButtonText(assuranceButtonGroup);
    }
    
    public String getUsure()
    {
        return getSelectedButtonText(usureButtonGroup);
    }
    
    // Fonctions pour le paneau de Véhicule
    public void setChoixClasse(String vehicule)
    {
        this.classeChoisieLabel.setText(vehicule);
    }
    
    public void setVehicule(String[] vehicule)
    {
        this.vehiculeDisponibleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(vehicule));
    }
    
    public String getVehiculeChoisi()
    {
        return this.vehiculeDisponibleComboBox.getSelectedItem().toString();
    }
    
    // Fonctions pour les informations clients
    public String getNumeroPermis()
    {
        return this.numeroPermisTextField.getText();
    }
    
    public String getPrenom()
    {
        return this.prenomTextField.getText();
    }
    
    public String getNom()
    {
        return this.nomTextField.getText();
    }
    
    public String getCourriel()
    {
        return this.courrielTextField.getText();
    }
    
    public String getTelephone()
    {
        return this.telephoneTextField.getText();
    }
    
    public String getDateNaissance()
    {
        return this.dateNaissanceTextField.getText();
    }
    
    public String getDateExpiration()
    {
        return this.dateExpirationPermisTextField.getText();
    }
    
    public String getClasse()
    {
        return getSelectedButtonText(classePermisButtonGroup);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assuranceButtonGroup = new javax.swing.ButtonGroup();
        usureButtonGroup = new javax.swing.ButtonGroup();
        classePermisButtonGroup = new javax.swing.ButtonGroup();
        informationLocationPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dateFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        dureeComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        classeComboBox = new javax.swing.JComboBox<>();
        assuranceLabel = new javax.swing.JLabel();
        personnelleButton = new javax.swing.JRadioButton();
        supplementPoliceButton = new javax.swing.JRadioButton();
        usureLabel = new javax.swing.JLabel();
        km500Button = new javax.swing.JRadioButton();
        kmIllimiteButton = new javax.swing.JRadioButton();
        choixVehiculeButton = new javax.swing.JButton();
        informationClientLocationPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        prenomTextField = new javax.swing.JTextField();
        nomTextField = new javax.swing.JTextField();
        courrielTextField = new javax.swing.JTextField();
        telephoneTextField = new javax.swing.JFormattedTextField();
        dateNaissanceTextField = new javax.swing.JFormattedTextField();
        dateExpirationPermisTextField = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        numeroPermisTextField = new javax.swing.JTextField();
        classe123RadioButton = new javax.swing.JRadioButton();
        classe45RadioButton = new javax.swing.JRadioButton();
        classeAutreRadioButton = new javax.swing.JRadioButton();
        vehiculeLocationPanel = new javax.swing.JPanel();
        vehiculeClasseLabel = new javax.swing.JLabel();
        classeChoisieLabel = new javax.swing.JLabel();
        vehiculeDisponibleLabel = new javax.swing.JLabel();
        vehiculeDisponibleComboBox = new javax.swing.JComboBox<>();
        confirmerLocationButton = new javax.swing.JButton();
        annulerLocationButton = new javax.swing.JButton();
        paiementLocationPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        modePaiementLocationComboBox = new javax.swing.JComboBox<>();
        calculLocationButton = new javax.swing.JButton();
        montantPaiementLocationPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        montantPremierVersementLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        paiementCautionLabel = new javax.swing.JLabel();
        payerLocationButton = new javax.swing.JButton();

        informationLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));

        jLabel5.setText("Date de location :");

        dateFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/YYYY"))));

        jLabel6.setText("Durée :");

        dureeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jour", "Semaine", "Mois" }));

        jLabel7.setText("Classe :");

        classeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economique", "Moyenne", "Confort", "Luxe", "Utilitaire" }));

        assuranceLabel.setText("Police d'assurance :");

        assuranceButtonGroup.add(personnelleButton);
        personnelleButton.setText("Personnelle");

        assuranceButtonGroup.add(supplementPoliceButton);
        supplementPoliceButton.setText("Supplementaire");

        usureLabel.setText("Frais d'usure (km) :");

        usureButtonGroup.add(km500Button);
        km500Button.setText("500");

        usureButtonGroup.add(kmIllimiteButton);
        kmIllimiteButton.setText("illimité");

        choixVehiculeButton.setText("Choix du Vehicule");
        choixVehiculeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixVehiculeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout informationLocationPanelLayout = new javax.swing.GroupLayout(informationLocationPanel);
        informationLocationPanel.setLayout(informationLocationPanelLayout);
        informationLocationPanelLayout.setHorizontalGroup(
            informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationLocationPanelLayout.createSequentialGroup()
                        .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informationLocationPanelLayout.createSequentialGroup()
                                .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(informationLocationPanelLayout.createSequentialGroup()
                                .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dureeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77))))
                    .addGroup(informationLocationPanelLayout.createSequentialGroup()
                        .addComponent(assuranceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(personnelleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supplementPoliceButton))
                    .addGroup(informationLocationPanelLayout.createSequentialGroup()
                        .addComponent(usureLabel)
                        .addGap(32, 32, 32)
                        .addComponent(km500Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kmIllimiteButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(choixVehiculeButton)
                .addContainerGap())
        );
        informationLocationPanelLayout.setVerticalGroup(
            informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationLocationPanelLayout.createSequentialGroup()
                        .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dureeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assuranceLabel)
                            .addComponent(personnelleButton)
                            .addComponent(supplementPoliceButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(informationLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usureLabel)
                            .addComponent(km500Button)
                            .addComponent(kmIllimiteButton)))
                    .addComponent(choixVehiculeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        informationClientLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Information client"));

        jLabel12.setText("Date de naissance du locataire :");

        jLabel13.setText("Date d'expiration du permis de conduire :");

        jLabel14.setText("Classe du permis de conduire :");

        jLabel15.setText("Prénom :");

        jLabel16.setText("Nom :");

        jLabel17.setText("Adresse courriel :");

        jLabel18.setText("Numéro de téléphone :");

        courrielTextField.setToolTipText("Entrer adresse couriel du client");
        courrielTextField.setMinimumSize(new java.awt.Dimension(6, 100));

        try {
            telephoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telephoneTextField.setToolTipText("Entrer le numéro de téléphone du client");

        dateNaissanceTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        dateNaissanceTextField.setToolTipText("Entrer la date de naissance du client");

        dateExpirationPermisTextField.setToolTipText("Entrer la date d'expiration du permis du client");

        jLabel1.setText("Numéro permis de conduire :");

        classePermisButtonGroup.add(classe123RadioButton);
        classe123RadioButton.setText("1,2,3");

        classePermisButtonGroup.add(classe45RadioButton);
        classe45RadioButton.setText("4,5");

        classePermisButtonGroup.add(classeAutreRadioButton);
        classeAutreRadioButton.setText("Autre");

        javax.swing.GroupLayout informationClientLocationPanelLayout = new javax.swing.GroupLayout(informationClientLocationPanel);
        informationClientLocationPanel.setLayout(informationClientLocationPanelLayout);
        informationClientLocationPanelLayout.setHorizontalGroup(
            informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateExpirationPermisTextField))
                    .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroPermisTextField))
                    .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNaissanceTextField))
                    .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                        .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(courrielTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, informationClientLocationPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(25, 25, 25)
                                    .addComponent(nomTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, informationClientLocationPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(informationClientLocationPanelLayout.createSequentialGroup()
                                .addComponent(classe123RadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(classe45RadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(classeAutreRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        informationClientLocationPanelLayout.setVerticalGroup(
            informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationClientLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(courrielTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeroPermisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dateNaissanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dateExpirationPermisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationClientLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classe123RadioButton)
                    .addComponent(classe45RadioButton)
                    .addComponent(classeAutreRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vehiculeLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Véhicule"));

        vehiculeClasseLabel.setText("Classe :");

        vehiculeDisponibleLabel.setText("Véhicule disponible :");

        vehiculeDisponibleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout vehiculeLocationPanelLayout = new javax.swing.GroupLayout(vehiculeLocationPanel);
        vehiculeLocationPanel.setLayout(vehiculeLocationPanelLayout);
        vehiculeLocationPanelLayout.setHorizontalGroup(
            vehiculeLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculeLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehiculeLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiculeLocationPanelLayout.createSequentialGroup()
                        .addComponent(vehiculeClasseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classeChoisieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vehiculeLocationPanelLayout.createSequentialGroup()
                        .addComponent(vehiculeDisponibleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vehiculeDisponibleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vehiculeLocationPanelLayout.setVerticalGroup(
            vehiculeLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculeLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehiculeLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiculeClasseLabel)
                    .addComponent(classeChoisieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiculeLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiculeDisponibleLabel)
                    .addComponent(vehiculeDisponibleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        confirmerLocationButton.setText("Confirmer");
        confirmerLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerLocationButtonActionPerformed(evt);
            }
        });
        confirmerLocationButton.setVisible(false);

        annulerLocationButton.setText("Annuler");
        annulerLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerLocationButtonActionPerformed(evt);
            }
        });

        paiementLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Paiement"));

        jLabel19.setText("Mode de paiement :");

        modePaiementLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espece", "Debit", "Credit" }));

        calculLocationButton.setText("Calcul");
        calculLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculLocationButtonActionPerformed(evt);
            }
        });

        montantPaiementLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Montant à payer"));

        jLabel23.setText("Premier versement :");

        jLabel24.setText("Caution :");

        payerLocationButton.setText("Payer");
        payerLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payerLocationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout montantPaiementLocationPanelLayout = new javax.swing.GroupLayout(montantPaiementLocationPanel);
        montantPaiementLocationPanel.setLayout(montantPaiementLocationPanelLayout);
        montantPaiementLocationPanelLayout.setHorizontalGroup(
            montantPaiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(montantPaiementLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(montantPaiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(montantPaiementLocationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(montantPremierVersementLabel))
                    .addGroup(montantPaiementLocationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paiementCautionLabel)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, montantPaiementLocationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payerLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        montantPaiementLocationPanelLayout.setVerticalGroup(
            montantPaiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(montantPaiementLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(montantPaiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(montantPremierVersementLabel))
                .addGap(18, 18, 18)
                .addGroup(montantPaiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(paiementCautionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payerLocationButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paiementLocationPanelLayout = new javax.swing.GroupLayout(paiementLocationPanel);
        paiementLocationPanel.setLayout(paiementLocationPanelLayout);
        paiementLocationPanelLayout.setHorizontalGroup(
            paiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paiementLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modePaiementLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paiementLocationPanelLayout.createSequentialGroup()
                .addComponent(calculLocationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(montantPaiementLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paiementLocationPanelLayout.setVerticalGroup(
            paiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paiementLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(modePaiementLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paiementLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(montantPaiementLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calculLocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        montantPaiementLocationPanel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(informationLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vehiculeLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(informationClientLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(confirmerLocationButton)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(annulerLocationButton)
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(paiementLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vehiculeLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(paiementLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmerLocationButton)
                            .addComponent(annulerLocationButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(informationLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(informationClientLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        vehiculeLocationPanel.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerLocationButtonActionPerformed
        Controller.retourAcceuil(this, annuler);
    }//GEN-LAST:event_annulerLocationButtonActionPerformed

    private void payerLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payerLocationButtonActionPerformed
        Controller.paiement(confirmerLocationButton);
    }//GEN-LAST:event_payerLocationButtonActionPerformed

    private void calculLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculLocationButtonActionPerformed
        Controller.calculLocation(montantPaiementLocationPanel);
    }//GEN-LAST:event_calculLocationButtonActionPerformed

    private void choixVehiculeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixVehiculeButtonActionPerformed
        Controller.choixVehicule(vehiculeLocationPanel);
    }//GEN-LAST:event_choixVehiculeButtonActionPerformed

    private void confirmerLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerLocationButtonActionPerformed
        Controller.confirmationLocation(this, confirmer);
    }//GEN-LAST:event_confirmerLocationButtonActionPerformed

    private JPanel annuler;
    private JPanel confirmer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerLocationButton;
    private javax.swing.ButtonGroup assuranceButtonGroup;
    private javax.swing.JLabel assuranceLabel;
    private javax.swing.JButton calculLocationButton;
    private javax.swing.JButton choixVehiculeButton;
    private javax.swing.JRadioButton classe123RadioButton;
    private javax.swing.JRadioButton classe45RadioButton;
    private javax.swing.JRadioButton classeAutreRadioButton;
    private javax.swing.JLabel classeChoisieLabel;
    private javax.swing.JComboBox<String> classeComboBox;
    private javax.swing.ButtonGroup classePermisButtonGroup;
    private javax.swing.JButton confirmerLocationButton;
    private javax.swing.JTextField courrielTextField;
    private javax.swing.JFormattedTextField dateExpirationPermisTextField;
    private javax.swing.JFormattedTextField dateFormattedTextField;
    private javax.swing.JFormattedTextField dateNaissanceTextField;
    private javax.swing.JComboBox<String> dureeComboBox;
    private javax.swing.JPanel informationClientLocationPanel;
    private javax.swing.JPanel informationLocationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton km500Button;
    private javax.swing.JRadioButton kmIllimiteButton;
    private javax.swing.JComboBox<String> modePaiementLocationComboBox;
    private javax.swing.JPanel montantPaiementLocationPanel;
    private javax.swing.JLabel montantPremierVersementLabel;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JTextField numeroPermisTextField;
    private javax.swing.JLabel paiementCautionLabel;
    private javax.swing.JPanel paiementLocationPanel;
    private javax.swing.JButton payerLocationButton;
    private javax.swing.JRadioButton personnelleButton;
    private javax.swing.JTextField prenomTextField;
    private javax.swing.JRadioButton supplementPoliceButton;
    private javax.swing.JFormattedTextField telephoneTextField;
    private javax.swing.ButtonGroup usureButtonGroup;
    private javax.swing.JLabel usureLabel;
    private javax.swing.JLabel vehiculeClasseLabel;
    private javax.swing.JComboBox<String> vehiculeDisponibleComboBox;
    private javax.swing.JLabel vehiculeDisponibleLabel;
    private javax.swing.JPanel vehiculeLocationPanel;
    // End of variables declaration//GEN-END:variables
}
