/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locationdevoiture;

import javax.swing.JPanel;

/**
 *
 * @author jb_wi
 */
public class RetourPanel extends javax.swing.JPanel {

    /**
     * Creates new form retourLocation
     */
    public RetourPanel() {
        initComponents();
    }
    
    public void setAnnuler(JPanel annuler)
    {
        this.annuler = annuler;
    }
    
    public void setConfirmer(JPanel confirmer)
    {
        this.confirmer = confirmer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reparationButtonGroup = new javax.swing.ButtonGroup();
        trouverLocationPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        trouverLocationTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        plaqueImmatriculationTextField = new javax.swing.JTextField();
        chercherLocationButton = new javax.swing.JButton();
        clientRetourPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        vehiculeRetourPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        kilometrageVehiculeTextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        niveauEssenceVehiculeTextField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        ouiReparationRadioButton = new javax.swing.JRadioButton();
        nonReparationRadioButton = new javax.swing.JRadioButton();
        reparationRetourPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reparationTextArea = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        montantReparationTextField = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        dateRetourTextField = new javax.swing.JFormattedTextField();
        paiementRetourPanel = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        calculRetourButton = new javax.swing.JButton();
        montantRetourPanel = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        methodePaiementRetourComboBox = new javax.swing.JComboBox<>();
        payerRetourButton = new javax.swing.JButton();
        confirmerRetourButton = new javax.swing.JButton();
        annulerRetourButton = new javax.swing.JButton();

        trouverLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche"));

        jLabel27.setText("Numéro de location :");

        jLabel28.setText("Plaque d'immatriculation du véhicule :");

        plaqueImmatriculationTextField.setToolTipText("Entrer le numero de plaque d'immatriculation du vehicule");

        chercherLocationButton.setText("Chercher");

        javax.swing.GroupLayout trouverLocationPanelLayout = new javax.swing.GroupLayout(trouverLocationPanel);
        trouverLocationPanel.setLayout(trouverLocationPanelLayout);
        trouverLocationPanelLayout.setHorizontalGroup(
            trouverLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trouverLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trouverLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(trouverLocationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trouverLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(trouverLocationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plaqueImmatriculationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chercherLocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );
        trouverLocationPanelLayout.setVerticalGroup(
            trouverLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trouverLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trouverLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(trouverLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(trouverLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(plaqueImmatriculationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(trouverLocationPanelLayout.createSequentialGroup()
                .addComponent(chercherLocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        clientRetourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Client"));

        jLabel29.setText("Nom :");

        jLabel30.setText("Date de naissance :");

        jLabel37.setText("jLabel37");

        jLabel38.setText("jLabel38");

        javax.swing.GroupLayout clientRetourPanelLayout = new javax.swing.GroupLayout(clientRetourPanel);
        clientRetourPanel.setLayout(clientRetourPanelLayout);
        clientRetourPanelLayout.setHorizontalGroup(
            clientRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientRetourPanelLayout.setVerticalGroup(
            clientRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientRetourPanelLayout.createSequentialGroup()
                .addGroup(clientRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel37))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        vehiculeRetourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Véhicule"));

        jLabel31.setText("jLabel31");

        jLabel32.setText("Kilométrage du véhicule :");

        kilometrageVehiculeTextField.setToolTipText("Entrer le kilométrage du véhicule retourné");

        jLabel33.setText("Niveau d'essence du véhicule :");

        niveauEssenceVehiculeTextField.setToolTipText("Entrer le niveau d'essence du véhicule retourné sous forme de %");

        jLabel34.setText("Réparations nécessaires :");

        reparationButtonGroup.add(ouiReparationRadioButton);
        ouiReparationRadioButton.setText("Oui");

        reparationButtonGroup.add(nonReparationRadioButton);
        nonReparationRadioButton.setText("Non");

        reparationRetourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Reparation"));

        reparationTextArea.setColumns(20);
        reparationTextArea.setRows(5);
        jScrollPane1.setViewportView(reparationTextArea);

        jLabel35.setText("Montant des réparations :");

        montantReparationTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        javax.swing.GroupLayout reparationRetourPanelLayout = new javax.swing.GroupLayout(reparationRetourPanel);
        reparationRetourPanel.setLayout(reparationRetourPanelLayout);
        reparationRetourPanelLayout.setHorizontalGroup(
            reparationRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reparationRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reparationRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(reparationRetourPanelLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(montantReparationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        reparationRetourPanelLayout.setVerticalGroup(
            reparationRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reparationRetourPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(reparationRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(montantReparationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel36.setText("Date de retour :");

        dateRetourTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout vehiculeRetourPanelLayout = new javax.swing.GroupLayout(vehiculeRetourPanel);
        vehiculeRetourPanel.setLayout(vehiculeRetourPanelLayout);
        vehiculeRetourPanelLayout.setHorizontalGroup(
            vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculeRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reparationRetourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(vehiculeRetourPanelLayout.createSequentialGroup()
                        .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addGroup(vehiculeRetourPanelLayout.createSequentialGroup()
                                .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kilometrageVehiculeTextField)
                                        .addComponent(niveauEssenceVehiculeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                    .addGroup(vehiculeRetourPanelLayout.createSequentialGroup()
                                        .addComponent(ouiReparationRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nonReparationRadioButton))))
                            .addGroup(vehiculeRetourPanelLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateRetourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        vehiculeRetourPanelLayout.setVerticalGroup(
            vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculeRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(dateRetourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(kilometrageVehiculeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(niveauEssenceVehiculeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiculeRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(ouiReparationRadioButton)
                    .addComponent(nonReparationRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reparationRetourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        paiementRetourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Paiement"));

        jLabel39.setText("Premier versement :");

        jLabel40.setText("Caution :");

        jLabel41.setText("jLabel41");

        jLabel42.setText("jLabel42");

        calculRetourButton.setText("Calcul");
        calculRetourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculRetourButtonActionPerformed(evt);
            }
        });

        montantRetourPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel43.setText("Total :");

        jLabel44.setText("Différence :");

        jLabel45.setText("jLabel45");

        jLabel46.setText("jLabel46");

        jLabel47.setText("Méthode de paiement :");

        methodePaiementRetourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espece", "Debit", "Credit" }));

        payerRetourButton.setText("Payer");

        javax.swing.GroupLayout montantRetourPanelLayout = new javax.swing.GroupLayout(montantRetourPanel);
        montantRetourPanel.setLayout(montantRetourPanelLayout);
        montantRetourPanelLayout.setHorizontalGroup(
            montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(montantRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(montantRetourPanelLayout.createSequentialGroup()
                        .addGroup(montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45)))
                    .addGroup(montantRetourPanelLayout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(methodePaiementRetourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, montantRetourPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payerRetourButton)
                .addContainerGap())
        );
        montantRetourPanelLayout.setVerticalGroup(
            montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(montantRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(montantRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(methodePaiementRetourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(payerRetourButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout paiementRetourPanelLayout = new javax.swing.GroupLayout(paiementRetourPanel);
        paiementRetourPanel.setLayout(paiementRetourPanelLayout);
        paiementRetourPanelLayout.setHorizontalGroup(
            paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paiementRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(montantRetourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paiementRetourPanelLayout.createSequentialGroup()
                        .addGroup(paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paiementRetourPanelLayout.createSequentialGroup()
                                .addGroup(paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel41)))
                            .addComponent(calculRetourButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paiementRetourPanelLayout.setVerticalGroup(
            paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paiementRetourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(paiementRetourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addComponent(calculRetourButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(montantRetourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        confirmerRetourButton.setText("Confirmer");

        annulerRetourButton.setText("Annuler");
        annulerRetourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerRetourButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vehiculeRetourPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trouverLocationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clientRetourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paiementRetourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(annulerRetourButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(confirmerRetourButton)))
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(trouverLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clientRetourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(vehiculeRetourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(paiementRetourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(confirmerRetourButton)
                                .addComponent(annulerRetourButton))))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calculRetourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculRetourButtonActionPerformed
        Controller.retourAcceuil(this, annuler);
    }//GEN-LAST:event_calculRetourButtonActionPerformed

    private void annulerRetourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerRetourButtonActionPerformed
        Controller.confirmationRetour(this, confirmer);
    }//GEN-LAST:event_annulerRetourButtonActionPerformed

    private JPanel annuler;
    private JPanel confirmer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerRetourButton;
    private javax.swing.JButton calculRetourButton;
    private javax.swing.JButton chercherLocationButton;
    private javax.swing.JPanel clientRetourPanel;
    private javax.swing.JButton confirmerRetourButton;
    private javax.swing.JFormattedTextField dateRetourTextField;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kilometrageVehiculeTextField;
    private javax.swing.JComboBox<String> methodePaiementRetourComboBox;
    private javax.swing.JFormattedTextField montantReparationTextField;
    private javax.swing.JPanel montantRetourPanel;
    private javax.swing.JTextField niveauEssenceVehiculeTextField;
    private javax.swing.JRadioButton nonReparationRadioButton;
    private javax.swing.JRadioButton ouiReparationRadioButton;
    private javax.swing.JPanel paiementRetourPanel;
    private javax.swing.JButton payerRetourButton;
    private javax.swing.JTextField plaqueImmatriculationTextField;
    private javax.swing.ButtonGroup reparationButtonGroup;
    private javax.swing.JPanel reparationRetourPanel;
    private javax.swing.JTextArea reparationTextArea;
    private javax.swing.JPanel trouverLocationPanel;
    private javax.swing.JTextField trouverLocationTextField;
    private javax.swing.JPanel vehiculeRetourPanel;
    // End of variables declaration//GEN-END:variables
}
